---
name: OmniQuest
version: 1.0.0-beta1
author:
- jaylac2000
- AmitxD
main: AmitxD\OmniQuest\OmniQuest
src-namespace-prefix: AmitxD\OmniQuest
api: 5.0.0
website: https://github.com/Amitminer/OmniQuest

permissions:
  omniquest.command.use:
    default: true
...