---
# {PLAYER} = Name of the player that finished the quest. ONLY WORKS ON REWARDS
# {QUEST} = Name of the quest. Only where they are!
# Types : move, breakblock, placeblock, kills, command

category-select-title: "§6§lOmni§a§lQuest"
category-select-content: "§f§lPlease select a category"
quest-select-content: "§f§lPlease choose a quest"
finished-quest-message: "§l§2§e[§d§lQuest§e]§2..§r§f GG, you finished the quest: §b§l{QUEST}"
button-leave: "§c§lLeave"
button-info-start: "§a§lStart the quest"
button-info-pause: "§e§lStop the quest"
quest-already-finished: "§l§2§6§lOmni§a§lQuest§r §c>>§r..§r§f You have already finished this quest!"
paused-quest: "§l§6Omni§aQuest§r §c>>§r You stopped the quest: §b§l{QUEST}"
started-quest: "§l§6Omni§aQuest§r §c>>§r You started the quest: §b§l{QUEST}"
quest-opened: "§7§lNot started"
quest-inprogress: "§a§lCurrent quest"
quest-finished: "§6§lCompleted"

categories:
  Mining:
    StoneMiner:
      name: "§7§lStone Miner"
      description: "§fMine §e§l100 §fstone blocks!"
      type: breakblock
      block: "stone"
      number: 100
      money: 250

  Combat:
    BeginnerSlayer:
      name: "§c§lBeginner Slayer"
      description: "§fEliminate §e§l5 §fplayers in battle!"
      type: kills
      number: 5
      money: 2500

  Commando:
    ExploreMine:
      name: "§l§3Explore Mine"
      description: "§fUse §e/mine §fto visit the mining area!"
      type: command
      command: "mine"
      rewards:
        - "give {PLAYER} iron_pickaxe 1"
        - "give {PLAYER} torch 16"

...
